### ISSUE TITLE
Error on linux

### ISSUE THREAD

**Issue by davejm** [pjworsley/capyle#1]
Hi, I'm in the COM2005 class. I use linux and my python 3.4 executable is symlinked to /usr/bin/python3. I.e. 'python3' is the command to run python 3.4 shell on my machine not 'python' (that would be python 2.7). I think this is pretty standard for UNIX systems.

I got it working by replacing 'python' on lines 22 and 56 of utils.py with 'sys.executable'. This should also work cross-platform.

I know your installation asks to use anaconda but I believe in many cases that python 3.4 will be 'python3' and so hardcoding will cause an error.

Cheers,
David

**Comment by pjworsley** [comment]
Hi David,

Thanks for picking that up. I alias my python3 to python, so forgot to consider this.
I will take a look at the fix, but it may not be implemented as it needs to work on University of Sheffield machines primarily. It _should_ work, but you never know with the managed desktops.

If the fix doesn't work I'll pop something in the documentation.

Cheers, 
Pete

**Comment by pjworsley** [comment]
Hi, 

All tested & fixed now, thank you very much for spotting that!

Pete

**Comment by davejm** [comment]
No problem. I think line 56 of utils.py should also be changed.

**Comment by pjworsley** [comment]
Whoops, forgot about that one, all done.
